name: crm-ventas-comida
region: nyc

databases:
  - name: db
    engine: PG
    version: "16"
    production: true
    cluster_name: crm-ventas-comida-db
    db_name: brunoweb
    db_user: brunoweb
    size: db-s-1vcpu-1gb
    num_nodes: 1

services:
  - name: web
    github:
      repo: juanmanuelrot/crm-ventas-comida
      branch: main
      deploy_on_push: true
    source_dir: /
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    build_command: npm run build
    run_command: npx prisma migrate deploy && npm start
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_URL}
      - key: AUTH_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: AUTH_TRUST_HOST
        scope: RUN_TIME
        value: "true"
      - key: ADMIN_EMAIL
        scope: RUN_TIME
        value: bruno@prueba.com
      - key: ADMIN_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: ADMIN_NAME
        scope: RUN_TIME
        value: Bruno
      - key: TIMEZONE
        scope: RUN_AND_BUILD_TIME
        value: America/Montevideo
